const DATA = [
  {
    Categoria: "Abarrotes",
    data: [
      [
        {
          id: 421,
          referencia: "1047",
          nombreProducto: "Colada maizena la original",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/COLADA MAIZENA LA ORIGINAL X 380 GR.PNG",
          costo_venta: 8800,
          unidad_medida: 380,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Harinas y mezclas listas",
          categoria: "Abarrotes",
        },
        {
          id: 422,
          referencia: "1051",
          nombreProducto: "Colada toning 7 cereales surtida",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/COLADA TONING 7 CEREALES SURTIDA.PNG",
          costo_venta: 2850,
          unidad_medida: 200,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Harinas y mezclas listas",
          categoria: "Abarrotes",
        },
      ],
    ],
  },
  {
    Categoria: "Lacteos y huevos",
    data: [
      [
        {
          id: 380,
          referencia: "964",
          nombreProducto: "Baby klim 2 lata",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/BABY KLIM 2 LATA.PNG",
          costo_venta: 21150,
          unidad_medida: 400,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
        {
          id: 381,
          referencia: "965",
          nombreProducto: "Baby klim 1 lata",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/BABY KLIM 1 LATA.PNG",
          costo_venta: 23800,
          unidad_medida: 400,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
        {
          id: 403,
          referencia: "1006",
          nombreProducto: "Klim - rodeo nutri rinde",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/KLIM / RODEO NUTRI RINDE.PNG",
          costo_venta: 20400,
          unidad_medida: 900,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
        {
          id: 404,
          referencia: "1007",
          nombreProducto: "Klim 1+",
          imagen: "http://haztupedido.co/moduloapi/categoria/KLIM 1+.PNG",
          costo_venta: 17200,
          unidad_medida: 500,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
        {
          id: 405,
          referencia: "1009",
          nombreProducto: "Klim 3+",
          imagen: "http://haztupedido.co/moduloapi/categoria/KLIM 3+.PNG",
          costo_venta: 16050,
          unidad_medida: 500,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
        {
          id: 406,
          referencia: "1011",
          nombreProducto: "Klim deslactosado",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/KLIM DESLACTOSADO.PNG",
          costo_venta: 12450,
          unidad_medida: 360,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Leche en polvo",
          categoria: "Lacteos y huevos",
        },
      ],
    ],
  },
  {
    Categoria: "Despensa",
    data: [
      [
        {
          id: 435,
          referencia: "1078",
          nombreProducto: "Choco krispis",
          imagen: "http://haztupedido.co/moduloapi/categoria/CHOCO KRISPIS.PNG",
          costo_venta: 20400,
          unidad_medida: 700,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Cereales",
          categoria: "Despensa",
        },
        {
          id: 436,
          referencia: "1079",
          nombreProducto: "Zucaritas",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/ZUCARITAS 300 GR.PNG",
          costo_venta: 8500,
          unidad_medida: 300,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Cereales",
          categoria: "Despensa",
        },
        {
          id: 437,
          referencia: "1080",
          nombreProducto: "Zukcaritas",
          imagen: "http://haztupedido.co/moduloapi/categoria/ZUCARITAS.PNG",
          costo_venta: 12250,
          unidad_medida: 450,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Cereales",
          categoria: "Despensa",
        },
        {
          id: 438,
          referencia: "1081",
          nombreProducto: "Choc okrispis pops",
          imagen:
            "http://haztupedido.co/moduloapi/categoria/CHOCO KRISPIS POPS.PNG",
          costo_venta: 8500,
          unidad_medida: 230,
          tipo_unidad: "GR",
          tieneDescuento: 0,
          descuentoD: 0,
          subcategoria: "Cereales",
          categoria: "Despensa",
        },
      ],
    ],
  },
];
